### ISSUE TITLE
got errors while compiling AdvancedTargeting

### ISSUE THREAD

**Issue by xiaooloong** [CSSZombieEscape/sm-plugins#1]
$ ./spcomp  AdvancedTargeting.sp 
SourcePawn Compiler 1.7.3-dev+5292
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2014 AlliedModders LLC

AdvancedTargeting.sp(28) : error 100: function prototypes do not match
AdvancedTargeting.sp(29) : error 100: function prototypes do not match
AdvancedTargeting.sp(30) : error 100: function prototypes do not match
AdvancedTargeting.sp(31) : error 100: function prototypes do not match
AdvancedTargeting.sp(52) : error 100: function prototypes do not match
AdvancedTargeting.sp(53) : error 100: function prototypes do not match
AdvancedTargeting.sp(54) : error 100: function prototypes do not match
AdvancedTargeting.sp(55) : error 100: function prototypes do not match

8 Errors.

**Comment by BotoX** [comment]
AdvancedTargeting requires a patched version of sourcemod for the @friends functionality to work.

Check out this commit: https://github.com/CSSZombieEscape/sourcemod/commit/ed73655c036d8310ff322138eac6180fd745d298
